### ISSUE TITLE
Overlay not displaying FFZ and BTTV emotes

### ISSUE THREAD

**Issue by kibeloko** [akhanubis/twitch_chat_overlay_issues#10]
Recently the overlay stopped showing the emotes, tried reinstalling but didn't work.

**Comment by akhanubis** [comment]
Do the emotes show in normal chat?
Do they show if you open a new tab with just the stream chat? Like this: https://www.twitch.tv/popout/bobross/chat

**Comment by kibeloko** [comment]
Yes every emote works both in normal and popout chat. They just stopped working in your overlay.

**Comment by akhanubis** [comment]
What browser and OS are you using?

**Comment by kibeloko** [comment]
I'm using Firefox 79.0 and Windows 10 Version 2004 Build 19041.388

**Comment by kibeloko** [comment]
> 
> 
> Hi guys! I'm using Firefox 79.0 and Windows 10 2004 19041.388, BetterTTV v7.2.85 works correctly.

Are you using only BTTV or is FFZ also working? I'm only using FFZ.

This is how it looks for me: [https://i.imgur.com/k6fMMia.jpeg](url)

**Comment by RogerUP13** [comment]
@kibeloko I am using only BTTV. Checked FFZ - does not work.

**Comment by akhanubis** [comment]
Great, thanks for the report! I'll look into it during the weekend.

**Comment by akhanubis** [comment]
Looks like FFZ fails to start when running a twitch iframe inside a twitch page.

As a workaround till that gets fixed, I added an option to show chat on top of the stream without using an iframe by adding the query string force_vod=true (e. g. https://www.twitch.tv/mizkif?force_vod=true). That should prevent FFZ from failing.

I'm closing this issue, but feel free to reopen it if it's not fixed.
