### ISSUE TITLE
Transparent background for re-subs and gift subs

### ISSUE THREAD

**Issue by RogerUP13** [akhanubis/twitch_chat_overlay_issues#11]
Could you please make re-subs and gift subs in a chat transparent like chat background when popup is not focused?
I suppose it is .tw-c-background-alt css style.
![Аннотация 2020-08-05 193335](https://user-images.githubusercontent.com/7015211/89439548-071fbf80-d753-11ea-8244-ad4dc3748c90.png)

**Comment by akhanubis** [comment]
Fixed (hopefully) in 0.2.6.
