### ISSUE TITLE
The chat overlay doesn't work in VODs anymore

### ISSUE THREAD

**Issue by InfinityXZERO** [akhanubis/twitch_chat_overlay_issues#12]
Recently after the update with the new Twitch layout, when I was watching VODs the chat overlay icon was now missing and it doesn't work anymore. But overall, it works fine when the Twitch channels are live, it just not the VODs.

**Comment by akhanubis** [comment]
Fixed in 0.2.6. You may need to refresh the page for it to work if you were previously watching a live stream with the overlay on.
