### ISSUE TITLE
Open overlay icon broken

### ISSUE THREAD

**Issue by RogerUP13** [akhanubis/twitch_chat_overlay_issues#13]
Hi, today I noticed that open overlay icon is displayed incorrectly. But I can click on it and the overlay opens successfully. Firefox 79.
![Аннотация 2020-08-12 104428](https://user-images.githubusercontent.com/7015211/89988931-e42c6880-dc88-11ea-8a2e-e783367770bf.png)

**Comment by akhanubis** [comment]
Fixed in 0.2.7
