### ISSUE TITLE
Make all messages background transparent.

### ISSUE THREAD

**Issue by thebluef0x** [akhanubis/twitch_chat_overlay_issues#19]
![obraz](https://user-images.githubusercontent.com/30621711/104118497-ed019300-5329-11eb-8076-f4ef48d13fcc.png)

Sorry if this is already implemented but I don't see the option anywhere in the settings.

**Comment by akhanubis** [comment]
![image](https://user-images.githubusercontent.com/2922430/105620441-ff74d580-5ddb-11eb-9acc-a111a8366584.png)

Seems that you have that BTTV option on. If you really need to have that enabled, I can upload a fix that makes every message transparent even when that option is on.

**Comment by thebluef0x** [comment]
You are right. No need for any fix then
