### ISSUE TITLE
Config option to not use iframe

### ISSUE THREAD

**Issue by OldManDan** [akhanubis/twitch_chat_overlay_issues#21]
The only way to fix the issue of BTTV/FFZ emotes not showing up in the overlay right now is to manually type `?force_vod=true` in the address bar after the channel url in order to make the addon not use an iframe. Could a config option to toggle iframe off be added to the addon settings?

**Comment by akhanubis** [comment]
Added in 0.3.0, you can find the option in the extension options panel

![image](https://user-images.githubusercontent.com/2922430/105620513-af4a4300-5ddc-11eb-9bf9-749f91b1c30e.png)
![image](https://user-images.githubusercontent.com/2922430/105620516-b2ddca00-5ddc-11eb-94a5-d71c5bdca469.png)

Feel free to reopen if there are any issues!
