### ISSUE TITLE
Doesn't work for vods

### ISSUE THREAD

**Issue by mdashlw** [akhanubis/twitch_chat_overlay_issues#22]
Overlay option is shown on main channel page in mini player for the past broadcast
![image](https://user-images.githubusercontent.com/34678047/105666007-51efe800-5ee9-11eb-9448-3b9ee2e3628d.png)

But not if you open the video (it exists for a split second and then disappears)
![image](https://user-images.githubusercontent.com/34678047/105666041-6a600280-5ee9-11eb-84a7-5e099ed3b3bc.png)

Tried turning force_vod on/off, no effect. Using firefox 84.0.2

**Comment by akhanubis** [comment]
I deployed a new version, 0.3.2, which should fix this. There are some issues with chat scroll, but at least it should work now.
