### ISSUE TITLE
ZOOMED IN SETTINGS 

### ISSUE THREAD

**Issue by robotX3iV** [akhanubis/twitch_chat_overlay_issues#29]
the settings a so zoomed-in you cant use them at all. "Settings are synced across your devices and stored on a per-stream basis.
Tip: Keep the chat window to the sides of the screen so you can preview your changes." This is all that's showing instead of the settings options. thank you.

**Comment by akhanubis** [comment]
I deployed a fix in version 0.3.9. Feel free to reopen if it's still broken
