### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by xardas-xyz** [akhanubis/twitch_chat_overlay_issues#33]
The button became too big.
![001](https://user-images.githubusercontent.com/99219935/152876719-d158e4f4-4cc1-4112-b780-b6d8c84d94ac.PNG)

**Comment by qq1ng** [comment]
bump, same here. chrome, 1080p, both in fullscreen and not

**Comment by akhanubis** [comment]
Fixed in 0.4.0. Feel free to reopen if issue persists
