### ISSUE TITLE
Button to open chat not appearing while watching Twitch after browser update.

### ISSUE THREAD

**Issue by PlutoPlays** [akhanubis/twitch_chat_overlay_issues#41]
The button to open the overlay doesn't show after updating chrome to version 105. Have tried restarting PC, reinstalling extension, restarting browser.

**Comment by akhanubis** [comment]
Hi, should be fixed in version 0.4.5. Let me know if it still doesnt work after updating to that version

**Comment by 71snack** [comment]
no problems, i'll let you know. Thank you in advance for your work bro. You make the best twitch chat overlay ^^

**Comment by 71snack** [comment]
working perfectly now thanks bro
