### ISSUE TITLE
7TV Emotes not showing

### ISSUE THREAD

**Issue by HanirTxZ** [akhanubis/twitch_chat_overlay_issues#44]
Since the last major 7tv update, 7tv emotes are not showing anymore.

**Comment by HanirTxZ** [comment]
nvm solved. just disabled 7tv extension and enabled 7tv from FFZ settings.

**Comment by akhanubis** [comment]
thanks for the report.
i'll reopen and look into it when I have a chance, because new 7tv suggests removing FFZ, so most people (myself included) won't have that workaround option.
