### ISSUE TITLE
Button is hilariously large

### ISSUE THREAD

**Issue by ryanull24** [akhanubis/twitch_chat_overlay_issues#49]
So, yesterday everything was fine, turned off PC, today the button looks like the image below - very large. The same issue on my laptop, both running W11 and Brave (v1.57.57). 1080p resolution

![image](https://github.com/akhanubis/twitch_chat_overlay_issues/assets/92233600/a1b8f6e9-9b57-4745-8e8f-82f4cf3db6ca)

**Comment by Vermoot** [comment]
Same here, happy to see I'm not the only one

**Comment by akhanubis** [comment]
Should be fixed in 0.4.9!
