### ISSUE TITLE
Button is enormous on firefox

### ISSUE THREAD

**Issue by ethantheb** [akhanubis/twitch_chat_overlay_issues#52]
![image](https://github.com/akhanubis/twitch_chat_overlay_issues/assets/41026336/01d37054-9e3e-4a50-931f-e63751194833)

**Comment by Vermoot** [comment]
Yep, this again :D

**Comment by akhanubis** [comment]
Ty for letting me know. I'm on vacation, will fix it prob during the
weekend.

**Comment by akhanubis** [comment]
Fixed in 0.4.10.
