### ISSUE TITLE
Some customization not working

### ISSUE THREAD

**Issue by Munzu** [akhanubis/twitch_chat_overlay_issues#9]
Some options don't seem to be working, such as 

- Background color
- Font family
- Font size
- Font color
- Font outline
- Font weight

When I change those options, nothing changes. 
The only options working for me are

- Placement
- Background opacity
- Auto-claim channel points

Firefox 78.0.2 (64-bit). Windows

**Comment by akhanubis** [comment]
Thanks for the report!
I was able to reproduce every bug except for Background color not working. Have you tried moving the right most slider (the one that controls transparency)?

**Comment by Munzu** [comment]
Oh yes, my bad, that works. That's what I originally meant by Background opacity.

**Comment by akhanubis** [comment]
Weird, I tried with the same Firefox version and OS and all the background customization options are working for me.
Anyway, I already submitted a new version (0.2.4) that should fix the font customization options, maybe background gets fixed too!

I'll go ahead and close the issue, but feel free to reopen it if it's still not working for you after updating the add-on to the new version.

**Comment by Munzu** [comment]
Wow, that was insanely fast. 
I figured out why my background color wasn't working. The left slider was all the way down instead of up. Sorry about the confusion! Everything's working now. Thank you so much!
